name: Build and Deploy
on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Cache node-modules üíΩ
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install and Build üîß
        run: |
          npm install --no-optional reveal-md
          mkdir build
          cp -r docs build/
          cp -r img build/
          ./node_modules/.bin/reveal-md --preprocessor includes.js --css custom.css --static build docs/session1a.md
          ./node_modules/.bin/reveal-md --preprocessor includes.js --css custom.css --static build docs/session1b.md
          ./node_modules/.bin/reveal-md --preprocessor includes.js --css custom.css --static build docs/session1c.md
          ./node_modules/.bin/reveal-md --preprocessor includes.js --css custom.css --static build docs/session2a.md
          ./node_modules/.bin/reveal-md --preprocessor includes.js --css custom.css --static build docs/session2b.md
          ./node_modules/.bin/reveal-md --preprocessor includes.js --css custom.css --static build docs/session2c.md
          ./node_modules/.bin/reveal-md --preprocessor includes.js --css custom.css --static build docs/session2d.md
          ./node_modules/.bin/reveal-md --preprocessor includes.js --css custom.css --static build docs/session3a.md
          ./node_modules/.bin/reveal-md --preprocessor includes.js --css custom.css --static build docs/session3b.md
          ./node_modules/.bin/reveal-md --preprocessor includes.js --css custom.css --static build docs/session4a.md
          ./node_modules/.bin/reveal-md --preprocessor includes.js --css custom.css --static build docs/session4b.md
          ./node_modules/.bin/reveal-md --preprocessor includes.js --css custom.css --static build docs/session4c.md
          ./node_modules/.bin/reveal-md --preprocessor includes.js --css custom.css --static build docs/session4d.md
          ./node_modules/.bin/reveal-md --preprocessor includes.js --css custom.css --static build docs/session5a.md
          ./node_modules/.bin/reveal-md --preprocessor includes.js --css custom.css --static build docs/session5b.md
          ./node_modules/.bin/reveal-md --preprocessor includes.js --css custom.css --static build docs/session6a.md
          ./node_modules/.bin/reveal-md --preprocessor includes.js --css custom.css --static build docs/session6b.md
          ./node_modules/.bin/reveal-md --preprocessor includes.js --css custom.css --static build docs/session6c.md
          ./node_modules/.bin/reveal-md --preprocessor includes.js --css custom.css --static build docs/session6d.md
          ./node_modules/.bin/reveal-md --preprocessor includes.js --css custom.css --static build slides.md
      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
